FROM python:3.11-slim
WORKDIR /app

# Installa le dipendenze di sistema
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY flask_app/ ./flask_app/
COPY flask_entrypoint.sh .
RUN chmod +x flask_entrypoint.sh

ENTRYPOINT ["/bin/sh", "/app/flask_entrypoint.sh"]
